### PR TITLE
Named logger

### PR DESCRIPTION
**Pull request by rocketraman**

### CODE REVIEW

**Comment by rocketraman** [comment]
@jvz FYI I've merged the `docs` branch here so I can add to the docs for the named logger.

**Comment by rocketraman** [comment]
Rebased on `master`.

**Comment by jvz** [comment]
The travis build is working now; looks like you're missing a license header.

**Comment by rocketraman** [comment]
@jvz Ironically, its actually the `.travis.yml` file you added to get the Travis build working :-) Do you want to fix that or should I?

**Comment by jvz** [comment]
Whoops! Sure, you can fix that, too.

**Pull request merged**
