### PR TITLE
Restore context correctly

### LINKED ISSUE #54: Coroutine context is not cleared properly
The coroutine context is not cleared properly. This test fails:

```kotlin
  @Test
  fun `Context is restored after a context block is complete`() = runBlocking {
    assertTrue(ContextMap.empty)
    assertTrue(ContextStack.empty)
    withContext(CoroutineThreadContext(ThreadContextData(mapOf("myKey" to "myValue"), listOf("test")))) {
      assertEquals("myValue", ContextMap["myKey"])
      assertEquals("test", ContextStack.peek())
    }
    assertTrue(ContextMap.empty)
    assertTrue(ContextStack.empty)
  }
```

### PR DESCRIPTION
**Pull request by rocketraman**
Fixes #54

### CODE REVIEW

**Comment by jvz** [comment]
@rocketraman can you sign your commits? You can use GPG, SSH, or SMIME for that (I use all three in various places).

**Comment by rocketraman** [comment]
> @rocketraman can you sign your commits? You can use GPG, SSH, or SMIME for that (I use all three in various places).

Yep. Do you want me to rebase this PR with a signed commit, or for the future only?

**Comment by rocketraman** [comment]
@jvz Is it possible to release a 1.3.1 with this change? I'm using it in a project which extensively uses logging contexts, and without this change, things are royally messed up.

**Comment by rocketraman** [comment]
> @rocketraman check this out https://logging.apache.org/logging-parent/latest/#release-instructions and see if you can start the release.

@jvz If I want to do a 1.3.1 release, what is the recommended approach in terms of branches?  Create branch release/1.3.1 of off tag `rel/1.3.0` and cherry-pick my change into it?

**Pull request merged**
