### PR TITLE
Add catching and throwing

### LINKED ISSUE #32: catching() is missing in KotlinLogger
It looks like `Logger.catching(..)` methods are missing in `KotlinLogger`.

If there is an equivalent for that then please mention it in _KDoc_ of `KotlinLogger` and / or at Log4j Kotlin project site.
Fix version `1.2.1` and `1.3` are acceptable.

Previously created at https://issues.apache.org/jira/browse/LOG4J2-3649

### PR DESCRIPTION
**Pull request by rocketraman**
Closes #32

### CODE REVIEW

**Review by jvz — COMMENTED** [review]
Can you add a changelog entry? Can copy an existing one in https://github.com/apache/logging-log4j-kotlin/tree/master/src/changelog/.1.x.x and reference the issue link there.

**Comment by rocketraman** [comment]
> Can you add a changelog entry? Can copy an existing one in https://github.com/apache/logging-log4j-kotlin/tree/master/src/changelog/.1.x.x and reference the issue link there.

I was going to do that but wanted to understand your plans for releasing first so as to give the correct information in the changelog. Your comment [in ](https://github.com/apache/logging-log4j-kotlin/pull/34#issuecomment-1430082484) makes things clear.

**Comment by jvz** [comment]
I've been meaning to post that to the dev list, too. Let me sum that up for there since we'll need some reviewers on those releases when they're cut.

**Comment by rocketraman** [comment]
Changelog added.

**Comment by jvz** [comment]
That directory gets automatically created when I cut a release; can you put it in the .1.x.x directory? This is a new system recently developed for the main log4j repo.

**Comment by rocketraman** [comment]
> That directory gets automatically created when I cut a release; can you put it in the .1.x.x directory? This is a new system recently developed for the main log4j repo.

Ah, that is much nicer. Done.

**Review by jvz — APPROVED** [review]

**Comment by jvz** [comment]
Sweet, that's about the last thing needed for 1.3.0 I think! Thanks!

**Pull request merged**
