### PR TITLE
Ensure OSGi compatibility

### PR DESCRIPTION
**Pull request by roedll**
We are using the Log4J Kotlin API in an OSGi environment. One pitfall is the missing manifest headers that would enable the direct usage as OSGi bundle. We are currently working with a workaraound, that wraps (repackages) the jar as a bundle and adds those headers on the fly.
But "native" support would be way better ;-)

To use a jar as an OSGi bundle, the manifest needs to have additional headers.
These headers describe the bundle and provide additional information.

This MR adds those headers and some additional Maven configuration to automaitcally add those headers into the resulting MANIFEST.MF file.

Some resources that deal with OSGi, manifest headers and "bundelization":
* https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html
* https://www.osgi.org/bundle-headers-reference/
* https://vaadin.com/docs/flow/advanced/tutorial-making-components-osgi-compatible.html
* https://bnd.bndtools.org/chapters/390-wrapping.html
* https://livebook.manning.com/book/osgi-in-depth/appendix-a/

### CODE REVIEW

**Comment by rocketraman** [comment]
Thanks for this. I'd like to see the `bnd` definition file in a subdirectory rather than at the root e.g. `bnd/log4j-kotlin-api.bnd`

```
    <configuration>
        <bndfile>bnd/log4j-kotlin-api.bnd</bndfile>
    </configuration>
```

**Review by rocketraman — APPROVED** [review]
LGTM

**Review by rocketraman — CHANGES_REQUESTED** [review]
Actually, correction, looks like the `log4j-kotlin-api.bnd` name is inconsistent. It should probable be something generic like `metadata.bnd` OR it should match the top-level directory `log4j-api-kotlin`.

**Comment by roedll** [comment]
The standard path for bnd metadata seems to be the "<module>/bnd.bnd" (like defined here https://bnd.bndtools.org/md/805-instructions.html in section "Headers")

I've now synchronized it with the "artifactId"...
It's now "<module>/bnd/<artifactId>.bnd"

**Review by rocketraman — APPROVED** [review]

**Comment by rocketraman** [comment]
@jvz This PR LGTM. Are there any hoops we need to jump through before merging?

**Comment by jvz** [comment]
Nah, go ahead. There might be some OSGi bugs in Log4j itself, but those
would be handled separately.

**Pull request merged**
