### PR TITLE
Kotlin minimum 1.4.30, coroutines 1.4.3

### PR DESCRIPTION
**Pull request by rocketraman**
Closes https://github.com/apache/logging-log4j-kotlin/issues/31.

### CODE REVIEW

**Comment by rocketraman** [comment]
@jvz I'm wondering if we should go directly to 1.6? Being two versions behind stable is not unreasonable. Or 1.5 alternatively.

**Comment by jvz** [comment]
I'd like to make a release of 1.3.0 without Kotlin 1.4 first, then 1.4.0 with Kotlin 1.4, then we can also update the baseline version requirement for a 1.5.0 release (could even match the Kotlin versions along the way like that). Now that the build has been more automated, cutting releases should be much easier (I've just been a little busy at work this month).

**Comment by rocketraman** [comment]
@jvz Ping on releasing 1.3.0? Or should we bother at this point? Kotlin is at 1.9.x now. We could probably skip to 1.7 without causing any undue issues.

**Comment by rocketraman** [comment]
Closing in favor of https://github.com/apache/logging-log4j-kotlin/pull/43

**Pull request closed without merging**
